.only-default: &only-default
  only:
    - master
    - develop
    - demo
    - merge_requests

#image: node:12-alpine
image: docker:19.03.1

services:
  - docker:19.03.1-dind

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./node_modules

variables:
  PROJECT_PATH: /builds/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - dependencies
  - build and deploy

install dependencies:
  <<: *only-default
  stage: dependencies
  script:
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn install"

deploy develop:
  stage: build and deploy
  only:
    - develop
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - apk update && apk add openssh rsync
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn run build --profile"
    - cp ci/Dockerfile Dockerfile
    - cp ci/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_DEV "
      docker rm -f cp1_front_dev &&
      docker rmi -f $APP_IMAGE_TAG_NAME &&
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker run --name cp1_front_dev --restart=on-failure:10 -d -p 80:80 $APP_IMAGE_TAG_NAME
      "


deploy demo:
  stage: build and deploy
  only:
    - demo
  variables:
    APP_IMAGE_TAG_NAME_DEMO: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}_demo"
  before_script:
    - apk update && apk add openssh rsync
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env.demo .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn run build --profile"
    - cp ci/Dockerfile Dockerfile
    - cp ci/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME_DEMO .
    - docker push $APP_IMAGE_TAG_NAME_DEMO
    - ssh $SERVER_USER@$SERVER_HOST_DEV "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker run --name cp1_front_dev_demo --restart=on-failure:10 -d -p 8090:80 $APP_IMAGE_TAG_NAME_DEMO
      "
#      docker rm -f cp1_front_dev_demo &&
#      docker rmi -f $APP_IMAGE_TAG_NAME_DEMO &&
