.only-default: &only-default
  only:
    - master
    - preprod
    - staging
    - merge_requests

image: docker:19.03.1

services:
  - docker:19.03.1-dind

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./node_modules

variables:
  PROJECT_PATH: /builds/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2

stages:
  - dependencies
  - tests
  - build and deploy

install dependencies:
  <<: *only-default
  stage: dependencies
  script:
    - docker run --rm -w="/app" -v $PWD:/app node:16.13.1-alpine sh -c "yarn install"

jest-tests:
  stage: tests
  image: node:16.13.1-alpine
  script:
    - yarn test --watchAll=false
  only:
    refs:
      - merge_requests

deploy preprod:
  stage: build and deploy
  only:
    - preprod
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    REACT_APP_ENV: preprod
  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_PP >> ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_HOST_PP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env.preprod .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:16.13.1-alpine sh -c "yarn run build --profile"
    - cp ci/preprod/Dockerfile Dockerfile
    - cp ci/preprod/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_PP "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker-compose -f /home/deltarm/client/docker-compose.preprod.yml pull &&
      docker-compose -f /home/deltarm/client/docker-compose.preprod.yml up -d --remove-orphans
      "

deploy staging:
  stage: build and deploy
  only:
    - staging
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    REACT_APP_ENV: staging
  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io
    - eval "$(ssh-agent -s)"
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" |tr -d '\r' |ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:16.13.1-alpine sh -c "yarn run build --profile"
    - cp ci/staging/Dockerfile Dockerfile
    - cp ci/staging/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_DEV "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker-compose -f /home/deltarm/client/docker-compose.staging.yml pull &&
      docker-compose -f /home/deltarm/client/docker-compose.staging.yml up -d --remove-orphans
      "

deploy prod:
  stage: build and deploy
  only:
    - master
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    REACT_APP_ENV: prod
  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_PROD >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - docker run --rm -w="/app" -v $PWD:/app node:16.13.1-alpine sh -c "yarn run build --profile"
    - cp ci/Dockerfile Dockerfile
    - cp ci/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_PROD "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker-compose -f /home/deltarm/client/docker-compose.yml pull &&
      docker-compose -f /home/deltarm/client/docker-compose.yml up -d --remove-orphans
      "
