.only-default: &only-default
  only:
    - master
    - preprod
    - develop
    - merge_requests

image: docker:19.03.1

services:
  - docker:19.03.1-dind

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./node_modules

variables:
  PROJECT_PATH: /builds/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2

stages:
  - dependencies
  - build and deploy

install dependencies:
  <<: *only-default
  stage: dependencies
  script:
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn install"

deploy preprod:
  stage: build and deploy
  only:
    - preprod
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_PP >> ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_HOST_PP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env.preprod .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn run build --profile"
    - cp ci/preprod/Dockerfile Dockerfile
    - cp ci/preprod/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_PP "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker pull $APP_IMAGE_TAG_NAME &&
      docker restart cp1_front_preprod
      "

deploy develop:
  stage: build and deploy
  only:
    - develop
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io 
    - eval "$(ssh-agent -s)"
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" |tr -d '\r' |ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_HOST_DEV >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - cp .env .env.production
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn run build --profile"
    - cp ci/dev/Dockerfile Dockerfile
    - cp ci/dev/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_DEV "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker pull $APP_IMAGE_TAG_NAME &&
      docker restart cp1_front_dev
      "

deploy prod:
  stage: build and deploy
  only:
    - master
  variables:
    APP_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

  before_script:
    - apk update && apk add openssh rsync curl
    - curl ifconfig.io
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST_PROD >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN
  script:
    - docker run --rm -w="/app" -v $PWD:/app node:12-alpine sh -c "yarn run build --profile"
    - cp ci/Dockerfile Dockerfile
    - cp ci/nginx.conf nginx.conf
    - docker build -t $APP_IMAGE_TAG_NAME .
    - docker push $APP_IMAGE_TAG_NAME
    - ssh $SERVER_USER@$SERVER_HOST_PROD "
      docker login $CI_REGISTRY_IMAGE -u $GITLAB_CI_USERNAME -p $GITLAB_CI_TOKEN &&
      docker pull $APP_IMAGE_TAG_NAME &&
      docker restart cp1_front_prod
      "
