// @ts-check
/// <reference types="cypress" />
/// <reference types="../../../../../../cypress/support/component" />
// NOTE: Run CLI:
// yarn cypress:run:component --browser chrome --config video=false --spec "src/Features/Edit/components/Control/Display/FormControl.job4.cy.tsx"

import React from 'react';
import { SetupTestsComponents } from '../../../../../../cypress/utils/SetupTestsComponents';

import { FormControls } from './FormControl';

describe('<FormControl />', function () {
  const chapters = [
    {
      controls: [
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 9998,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Objectif du contrôle ',
          control_type: 'long_text',
          control_value:
            "S'assurer que les signataires /  délégataires soient bien formalisés",
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 9999,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'UO responsable du contrôle',
          control_type: 'long_text',
          control_value: 'Direction du Pilotage des Couts et Reporting',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10000,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Macro processus',
          control_type: 'long_text',
          control_value: 'CDG - Gérer les reporting et les couts',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10001,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Processus',
          control_type: 'long_text',
          control_value: 'Suivre les signatures autorisées',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10002,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Risque(s) associé(s)',
          control_type: 'long_text',
          control_value:
            "RIS_001557 - 7.1.2. Erreur ou défaillance dans la saisie, la mise en place ou la réalisation d'une opération",
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10003,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Niveau de contrôle',
          control_type: 'long_text',
          control_value: 'CP1_a_priori',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10004,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Type de contrôle',
          control_type: 'text',
          control_value: 'Auto-contrôle',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10005,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Périodicité',
          control_type: 'text',
          control_value: "au fil de l'eau",
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10006,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Données utiles au contrôle',
          control_type: 'long_text',
          control_value: '- Fichiers Excel et Word',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10007,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Contrôle majeur',
          control_type: 'text',
          control_value: 'Oui',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10008,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Validation Hiérarchique',
          control_type: 'text',
          control_value: 'Oui',
          editable: false,
          mandatory: false,
        },
        {
          control_conditional: false,
          control_desc_1: null,
          control_desc_2: null,
          control_editable: false,
          control_family: 'standard',
          control_id: 10009,
          control_manage_compliance: false,
          control_mandatory: false,
          control_options: null,
          control_pg_base_type: 'text',
          control_previous_value: null,
          control_regex: null,
          control_regex_msg: null,
          control_title: 'Calcul Résultat',
          control_type: 'text',
          control_value: 'Binaire',
          editable: false,
          mandatory: false,
        },
      ],
      id: '1',
      label: 'Identification du contrôle',
    },
  ];

  it('should render without crash', function () {
    const _chapters = structuredClone(chapters);

    cy.viewport(1920, 1080);
    cy.mount(
      <SetupTestsComponents>
        <FormControls chapters={_chapters} context={'edit'} />
      </SetupTestsComponents>,
    ).waitReactApp();
    cy.react('FormControls').should('exist');
  });
});
