import { injectCalculatedFields } from '../src/injectCalculatedFields';
import { IChapter } from '../../../Features/Edit/types';
const chapters: IChapter[] = [
  {
    label: 'Fake chapter 5',
    id: '5',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        editable: true,
        control_family: 'standard',
        control_id: '2307',
        control_manage_compliance: false,
        control_mandatory: false,
        mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_A',
        control_type: 'decimal',
        control_value: '5',
        control_options: null,
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 6',
    id: '6',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        editable: true,
        control_family: 'standard',
        control_id: '2308',
        control_manage_compliance: false,
        control_mandatory: false,
        mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_B',
        control_type: 'decimal',
        control_value: '5',
        control_options: null,
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 7',
    id: '7',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        editable: true,
        mandatory: false,
        control_options: null,
        control_family: 'standard',
        control_id: '2309',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_C',
        control_type: 'decimal',
        control_value: '5',
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 8',
    id: '8',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        editable: false,
        mandatory: false,
        control_options: null,
        control_family: 'formula',
        control_id: '2310',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé : (A + B) * C',
        control_type: 'formula',
        control_value: null,
        upload_detail: null,
        formula: {
          formula: '(#2307+#2308)*#2309',
          map: null,
        },
      },
    ],
  },
  {
    label: 'Fake chapter 9',
    id: '9',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        editable: false,
        mandatory: false,
        control_options: null,
        control_family: 'formula',
        control_id: '2311',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé: (A - B) / C',
        control_type: 'formula',
        control_value: null,
        upload_detail: null,
        formula: {
          formula: '(#2307-#2308)/#2309',
          map: null,
        },
      },
    ],
  },
  {
    label: 'Fake chapter 10',
    id: '10',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        editable: false,
        mandatory: false,
        control_options: null,
        control_family: 'formula',
        control_id: '2312',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé : (A / B) * 100',
        control_type: 'formula',
        control_value: null,
        upload_detail: null,
        formula: {
          formula: '(#2307/#2308)*100',
          map: null,
        },
      },
    ],
  },
  {
    label: 'Fake chapter 11',
    id: '11',
    controls: [
      {
        control_answer_choices: [
          {
            choice_id: 1,
            choice_is_ko: false,
            choice_lib: 'Conforme',
            choice_value: 1,
          },
          {
            choice_id: 2,
            choice_is_ko: true,
            choice_lib: 'Non-Conforme',
            choice_value: 0,
          },
          {
            choice_id: 3,
            choice_is_ko: false,
            choice_lib: 'Sans Objet',
            choice_value: 0,
          },
        ],
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        editable: true,
        mandatory: false,
        control_options: null,
        control_family: 'standard',
        control_id: '2313',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'int',
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Valeur D : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
        control_type: 'select_list',
        control_value: '1',
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 12',
    id: '12',
    controls: [
      {
        control_answer_choices: [
          {
            choice_id: 1,
            choice_is_ko: false,
            choice_lib: 'Conforme',
            choice_value: 1,
          },
          {
            choice_id: 2,
            choice_is_ko: true,
            choice_lib: 'Non-Conforme',
            choice_value: 0,
          },
          {
            choice_id: 3,
            choice_is_ko: false,
            choice_lib: 'Sans Objet',
            choice_value: 0,
          },
        ],
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        editable: true,
        mandatory: false,
        control_options: null,
        control_family: 'standard',
        control_id: '2314',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'int',
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Valeur E : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
        control_type: 'select_list',
        control_value: '1',
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 13',
    id: '13',
    controls: [
      {
        control_answer_choices: [
          {
            choice_id: 1,
            choice_is_ko: false,
            choice_lib: 'Conforme',
            choice_value: 1,
          },
          {
            choice_id: 2,
            choice_is_ko: true,
            choice_lib: 'Non-Conforme',
            choice_value: 0,
          },
          {
            choice_id: 3,
            choice_is_ko: false,
            choice_lib: 'Sans Objet',
            choice_value: 0,
          },
        ],
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        control_family: 'standard',
        control_id: '2315',
        editable: true,
        mandatory: false,
        control_options: null,
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'int',
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Valeur F : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
        control_type: 'select_list',
        control_value: '1',
        upload_detail: null,
      },
    ],
  },
  {
    label: 'Fake chapter 14',
    id: '14',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        control_family: 'formula',
        control_id: '2316',
        editable: false,
        mandatory: false,
        control_options: null,
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title:
          'Avg_Simple(D;E;F) : Pas de coef ; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
        control_type: 'formula',
        control_value: null,
        upload_detail: null,
        formula: {
          formula: '(#2313+#2314+#2315)/3',
          map: [
            {
              color: 'red',
              lib: 'Mauvais',
              max: 50,
              min: 0,
            },
            {
              color: 'orange',
              lib: 'Moyen',
              max: 80,
              min: 50,
            },
            {
              color: 'yellow',
              lib: 'Bon',
              max: 95,
              min: 80,
            },
            {
              color: 'green',
              lib: 'Excellent',
              max: 999,
              min: 95,
            },
          ],
        },
      },
    ],
  },
  {
    label: 'Fake chapter 15',
    id: '15',
    controls: [
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        editable: false,
        mandatory: false,
        control_options: null,
        control_family: 'formula',
        control_id: '2317',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title:
          'Avg_Coef(D;E;F) : Coef =>10-20-70; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
        control_type: 'formula',
        control_value: null,
        upload_detail: null,
        formula: {
          formula: '(#2313*10+#2314*20+#2315*70)/100',
          map: [
            {
              color: 'red',
              lib: 'Mauvais',
              max: 50,
              min: 0,
            },
            {
              color: 'orange',
              lib: 'Moyen',
              max: 80,
              min: 50,
            },
            {
              color: 'yellow',
              lib: 'Bon',
              max: 95,
              min: 80,
            },
            {
              color: 'green',
              lib: 'Excellent',
              max: 999,
              min: 95,
            },
          ],
        },
      },
    ],
  },
];

describe('Inject calculated fields into the form', () => {
  const mockFn = jest.fn((controls) => controls);
  it('Set the values of fields with the calculation of others', () => {
    const result = injectCalculatedFields(chapters);
    expect(result).toStrictEqual([
      {
        label: 'Fake chapter 5',
        id: '5',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2307',
            control_manage_compliance: false,
            control_mandatory: false,
            control_options: null,
            editable: true,
            mandatory: false,
            control_pg_base_type: 'double precision',
            control_previous_value: null,
            control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
            control_regex_msg:
              "La valeur saisie n'est pas une valeur autorisée pour ce champ",
            control_title: 'Champ calc_A',
            control_type: 'decimal',
            control_value: '5',
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 6',
        id: '6',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2308',
            control_manage_compliance: false,
            control_mandatory: false,
            editable: true,
            mandatory: false,
            control_options: null,
            control_pg_base_type: 'double precision',
            control_previous_value: null,
            control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
            control_regex_msg:
              "La valeur saisie n'est pas une valeur autorisée pour ce champ",
            control_title: 'Champ calc_B',
            control_type: 'decimal',
            control_value: '5',
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 7',
        id: '7',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2309',
            editable: true,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_options: null,
            control_pg_base_type: 'double precision',
            control_previous_value: null,
            control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
            control_regex_msg:
              "La valeur saisie n'est pas une valeur autorisée pour ce champ",
            control_title: 'Champ calc_C',
            control_type: 'decimal',
            control_value: '5',
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 8',
        id: '8',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: false,
            control_family: 'formula',
            control_id: '2310',
            control_manage_compliance: false,
            control_mandatory: false,
            editable: false,
            mandatory: false,
            control_pg_base_type: null,
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            control_title: 'Calculé : (A + B) * C',
            control_type: 'formula',
            control_value: '50',
            upload_detail: null,
            formula: {
              formula: '(#2307+#2308)*#2309',
              map: null,
            },
          },
        ],
      },
      {
        label: 'Fake chapter 9',
        id: '9',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: false,
            control_family: 'formula',
            control_id: '2311',
            control_manage_compliance: false,
            control_mandatory: false,
            editable: false,
            mandatory: false,
            control_pg_base_type: null,
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            control_title: 'Calculé: (A - B) / C',
            control_type: 'formula',
            control_value: '0',
            upload_detail: null,
            formula: {
              formula: '(#2307-#2308)/#2309',
              map: null,
            },
          },
        ],
      },
      {
        label: 'Fake chapter 10',
        id: '10',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: false,
            control_family: 'formula',
            control_id: '2312',
            editable: false,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: null,
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            control_title: 'Calculé : (A / B) * 100',
            control_type: 'formula',
            control_value: '100',
            upload_detail: null,
            formula: {
              formula: '(#2307/#2308)*100',
              map: null,
            },
          },
        ],
      },
      {
        label: 'Fake chapter 11',
        id: '11',
        controls: [
          {
            control_answer_choices: [
              {
                choice_id: 1,
                choice_is_ko: false,
                choice_lib: 'Conforme',
                choice_value: 1,
              },
              {
                choice_id: 2,
                choice_is_ko: true,
                choice_lib: 'Non-Conforme',
                choice_value: 0,
              },
              {
                choice_id: 3,
                choice_is_ko: false,
                choice_lib: 'Sans Objet',
                choice_value: 0,
              },
            ],
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2313',
            editable: true,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: 'int',
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            control_title:
              'Valeur D : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
            control_type: 'select_list',
            control_value: '1',
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 12',
        id: '12',
        controls: [
          {
            control_answer_choices: [
              {
                choice_id: 1,
                choice_is_ko: false,
                choice_lib: 'Conforme',
                choice_value: 1,
              },
              {
                choice_id: 2,
                choice_is_ko: true,
                choice_lib: 'Non-Conforme',
                choice_value: 0,
              },
              {
                choice_id: 3,
                choice_is_ko: false,
                choice_lib: 'Sans Objet',
                choice_value: 0,
              },
            ],
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2314',
            editable: true,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: 'int',
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            control_title:
              'Valeur E : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
            control_type: 'select_list',
            control_value: '1',
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 13',
        id: '13',
        controls: [
          {
            control_answer_choices: [
              {
                choice_id: 1,
                choice_is_ko: false,
                choice_lib: 'Conforme',
                choice_value: 1,
              },
              {
                choice_id: 2,
                choice_is_ko: true,
                choice_lib: 'Non-Conforme',
                choice_value: 0,
              },
              {
                choice_id: 3,
                choice_is_ko: false,
                choice_lib: 'Sans Objet',
                choice_value: 0,
              },
            ],
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: true,
            control_family: 'standard',
            control_id: '2315',
            editable: true,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: 'int',
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_title:
              'Valeur F : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
            control_type: 'select_list',
            control_value: '1',
            control_options: null,
            upload_detail: null,
          },
        ],
      },
      {
        label: 'Fake chapter 14',
        id: '14',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: false,
            control_family: 'formula',
            control_id: '2316',
            editable: false,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: null,
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            upload_detail: null,
            control_title:
              'Avg_Simple(D;E;F) : Pas de coef ; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
            control_type: 'formula',
            control_value: 'Mauvais',
            formula: {
              formula: '(#2313+#2314+#2315)/3',
              map: [
                {
                  color: 'red',
                  lib: 'Mauvais',
                  max: 50,
                  min: 0,
                },
                {
                  color: 'orange',
                  lib: 'Moyen',
                  max: 80,
                  min: 50,
                },
                {
                  color: 'yellow',
                  lib: 'Bon',
                  max: 95,
                  min: 80,
                },
                {
                  color: 'green',
                  lib: 'Excellent',
                  max: 999,
                  min: 95,
                },
              ],
            },
          },
        ],
      },
      {
        label: 'Fake chapter 15',
        id: '15',
        controls: [
          {
            control_conditional: false,
            control_desc_1: 'null',
            control_desc_2: null,
            control_editable: false,
            control_family: 'formula',
            control_id: '2317',
            editable: false,
            mandatory: false,
            control_manage_compliance: false,
            control_mandatory: false,
            control_pg_base_type: null,
            control_previous_value: null,
            control_regex: null,
            control_regex_msg: null,
            control_options: null,
            upload_detail: null,
            control_title:
              'Avg_Coef(D;E;F) : Coef =>10-20-70; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
            control_type: 'formula',
            control_value: 'Mauvais',
            formula: {
              formula: '(#2313*10+#2314*20+#2315*70)/100',
              map: [
                {
                  color: 'red',
                  lib: 'Mauvais',
                  max: 50,
                  min: 0,
                },
                {
                  color: 'orange',
                  lib: 'Moyen',
                  max: 80,
                  min: 50,
                },
                {
                  color: 'yellow',
                  lib: 'Bon',
                  max: 95,
                  min: 80,
                },
                {
                  color: 'green',
                  lib: 'Excellent',
                  max: 999,
                  min: 95,
                },
              ],
            },
          },
        ],
      },
    ]);
  });
  it('Return controls', () => {
    mockFn(chapters);
    expect(mockFn).toBeCalled();
    expect(mockFn).toHaveReturned();
  });
});
