import { injectCalculatedFields } from '../src/injectCalculatedFields';
import { IApiControl } from '../../../Features/Edit/types';
const controls: IApiControl[] = [
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: true,
    control_family: 'standard',
    control_id: '2307',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: 'double precision',
    control_previous_value: null,
    control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
    control_regex_msg:
      "La valeur saisie n'est pas une valeur autorisée pour ce champ",
    control_title: 'Champ calc_A',
    control_type: 'decimal',
    control_value: '5',
  },
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: true,
    control_family: 'standard',
    control_id: '2308',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: 'double precision',
    control_previous_value: null,
    control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
    control_regex_msg:
      "La valeur saisie n'est pas une valeur autorisée pour ce champ",
    control_title: 'Champ calc_B',
    control_type: 'decimal',
    control_value: '5',
  },
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: true,
    control_family: 'standard',
    control_id: '2309',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: 'double precision',
    control_previous_value: null,
    control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
    control_regex_msg:
      "La valeur saisie n'est pas une valeur autorisée pour ce champ",
    control_title: 'Champ calc_C',
    control_type: 'decimal',
    control_value: '5',
  },
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: false,
    control_family: 'formula',
    control_id: '2310',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: null,
    control_previous_value: null,
    control_regex: null,
    control_regex_msg: null,
    control_title: 'Calculé : (A + B) * C',
    control_type: 'formula',
    control_value: null,
    formula: {
      formula: '(#2307+#2308)*#2309',
      map: null,
    },
  },
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: false,
    control_family: 'formula',
    control_id: '2311',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: null,
    control_previous_value: null,
    control_regex: null,
    control_regex_msg: null,
    control_title: 'Calculé: (A - B) / C',
    control_type: 'formula',
    control_value: null,
    formula: {
      formula: '(#2307-#2308)/#2309',
      map: null,
    },
  },
  {
    control_conditional: false,
    control_desc_1: 'null',
    control_desc_2: null,
    control_editable: false,
    control_family: 'formula',
    control_id: '2312',
    control_manage_compliance: false,
    control_mandatory: false,
    control_pg_base_type: null,
    control_previous_value: null,
    control_regex: null,
    control_regex_msg: null,
    control_title: 'Calculé : (A / B) * 100',
    control_type: 'formula',
    control_value: null,
    formula: {
      formula: '(#2307/#2308)*100',
      map: null,
    },
  },
  // {
  //   control_answer_choices: [
  //     {
  //       choice_id: '1',
  //       choice_is_ko: false,
  //       choice_lib: 'Conforme',
  //     },
  //     {
  //       choice_id: '2',
  //       choice_is_ko: true,
  //       choice_lib: 'Non-Conforme',
  //     },
  //     {
  //       choice_id: '3',
  //       choice_is_ko: false,
  //       choice_lib: 'Sans Objet',
  //     },
  //   ],
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: true,
  //   control_family: 'standard',
  //   control_id: '2313',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: 'int',
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title: 'Valeur D : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
  //   control_type: 'selectlist',
  //   control_value: null,
  //   answerChoices: {
  //     '1': {
  //       id: '1',
  //       label: 'Conforme',
  //       value: '1',
  //       isKo: false,
  //     },
  //     '2': {
  //       id: '2',
  //       label: 'Non-Conforme',
  //       value: '2',
  //       isKo: true,
  //     },
  //     '3': {
  //       id: '3',
  //       label: 'Sans Objet',
  //       value: '3',
  //       isKo: false,
  //     },
  //   },
  // },
  // {
  //   control_answer_choices: [
  //     {
  //       choice_id: '1',
  //       choice_is_ko: false,
  //       choice_lib: 'Conforme',
  //     },
  //     {
  //       choice_id: '2',
  //       choice_is_ko: true,
  //       choice_lib: 'Non-Conforme',
  //     },
  //     {
  //       choice_id: '3',
  //       choice_is_ko: false,
  //       choice_lib: 'Sans Objet',
  //     },
  //   ],
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: true,
  //   control_family: 'standard',
  //   control_id: '2314',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: 'int',
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title: 'Valeur E : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
  //   control_type: 'selectlist',
  //   control_value: null,
  //   answerChoices: {
  //     '1': {
  //       id: '1',
  //       label: 'Conforme',
  //       value: '1',
  //       isKo: false,
  //     },
  //     '2': {
  //       id: '2',
  //       label: 'Non-Conforme',
  //       value: '2',
  //       isKo: true,
  //     },
  //     '3': {
  //       id: '3',
  //       label: 'Sans Objet',
  //       value: '3',
  //       isKo: false,
  //     },
  //   },
  // },
  // {
  //   control_answer_choices: [
  //     {
  //       choice_id: '1',
  //       choice_is_ko: false,
  //       choice_lib: 'Conforme',
  //     },
  //     {
  //       choice_id: '2',
  //       choice_is_ko: true,
  //       choice_lib: 'Non-Conforme',
  //     },
  //     {
  //       choice_id: '3',
  //       choice_is_ko: false,
  //       choice_lib: 'Sans Objet',
  //     },
  //   ],
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: true,
  //   control_family: 'standard',
  //   control_id: '2315',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: 'int',
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title: 'Valeur F : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
  //   control_type: 'selectlist',
  //   control_value: null,
  //   answerChoices: {
  //     '1': {
  //       id: '1',
  //       label: 'Conforme',
  //       value: '1',
  //       isKo: false,
  //     },
  //     '2': {
  //       id: '2',
  //       label: 'Non-Conforme',
  //       value: '2',
  //       isKo: true,
  //     },
  //     '3': {
  //       id: '3',
  //       label: 'Sans Objet',
  //       value: '3',
  //       isKo: false,
  //     },
  //   },
  // },
  // {
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: false,
  //   control_family: 'formula',
  //   control_id: '2316',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: null,
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title:
  //     'Avg_Simple(D;E;F) : Pas de coef ; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
  //   control_type: 'formula',
  //   control_value: null,
  //   formula: {
  //     formula: '(#2313+#2314+#2315)/3',
  //     map: null,
  //   },
  // },
  // {
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: false,
  //   control_family: 'formula',
  //   control_id: '2317',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: null,
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title:
  //     'Avg_Coef(D;E;F) : Coef =>10-20-70; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
  //   control_type: 'formula',
  //   control_value: null,
  //   formula: {
  //     formula: '(#2313*10+#2314*20+#2315*70)/100',
  //     map: null,
  //   },
  // },
  // {
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: false,
  //   control_family: 'formula',
  //   control_id: '2318',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: null,
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title:
  //     'Avg_Coef(D;E;F) : Coef =>25-50-25; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
  //   control_type: 'formula',
  //   control_value: null,
  //   formula: {
  //     formula: '(#2313*25+#2314*50+#2315*25)/100',
  //     map: null,
  //   },
  // },
  // {
  //   control_conditional: false,
  //   control_desc_1: 'null',
  //   control_desc_2: null,
  //   control_editable: false,
  //   control_family: 'formula',
  //   control_id: '2319',
  //   control_manage_compliance: false,
  //   control_mandatory: false,
  //   control_pg_base_type: null,
  //   control_previous_value: null,
  //   control_regex: null,
  //   control_regex_msg: null,
  //   control_title: 'Contagion (D;E;F) ; Conforme/Non-Conforme',
  //   control_type: 'formula',
  //   control_value: null,
  //   formula: {
  //     formula: '(#2313+#2314+#2315)/3',
  //     map: null,
  //   },
  // },
];

describe('Inject calculated fields into the form', () => {
  const mockFn = jest.fn((controls) => controls);
  it('Set the values of fields with the calculation of others', () => {
    const result = injectCalculatedFields(controls);
    expect(result).toStrictEqual([
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        control_family: 'standard',
        control_id: '2307',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_A',
        control_type: 'decimal',
        control_value: '5',
      },
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        control_family: 'standard',
        control_id: '2308',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_B',
        control_type: 'decimal',
        control_value: '5',
      },
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: true,
        control_family: 'standard',
        control_id: '2309',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: 'double precision',
        control_previous_value: null,
        control_regex: new RegExp('^-?[0-9]\\d*(\\.\\d+)?$'),
        control_regex_msg:
          "La valeur saisie n'est pas une valeur autorisée pour ce champ",
        control_title: 'Champ calc_C',
        control_type: 'decimal',
        control_value: '5',
      },
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        control_family: 'formula',
        control_id: '2310',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé : (A + B) * C',
        control_type: 'formula',
        control_value: '50',
        formula: {
          formula: '(#2307+#2308)*#2309',
          map: null,
        },
      },
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        control_family: 'formula',
        control_id: '2311',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé: (A - B) / C',
        control_type: 'formula',
        control_value: '0',
        formula: {
          formula: '(#2307-#2308)/#2309',
          map: null,
        },
      },
      {
        control_conditional: false,
        control_desc_1: 'null',
        control_desc_2: null,
        control_editable: false,
        control_family: 'formula',
        control_id: '2312',
        control_manage_compliance: false,
        control_mandatory: false,
        control_pg_base_type: null,
        control_previous_value: null,
        control_regex: null,
        control_regex_msg: null,
        control_title: 'Calculé : (A / B) * 100',
        control_type: 'formula',
        control_value: '100',
        formula: {
          formula: '(#2307/#2308)*100',
          map: null,
        },
      },
      // {
      //   control_answer_choices: [
      //     {
      //       choice_id: '1',
      //       choice_is_ko: false,
      //       choice_lib: 'Conforme',
      //     },
      //     {
      //       choice_id: '2',
      //       choice_is_ko: true,
      //       choice_lib: 'Non-Conforme',
      //     },
      //     {
      //       choice_id: '3',
      //       choice_is_ko: false,
      //       choice_lib: 'Sans Objet',
      //     },
      //   ],
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: true,
      //   control_family: 'standard',
      //   control_id: '2313',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: 'int',
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title: 'Valeur D : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
      //   control_type: 'selectlist',
      //   control_value: null,
      //   answerChoices: {
      //     '1': {
      //       id: '1',
      //       label: 'Conforme',
      //       value: '1',
      //       isKo: false,
      //     },
      //     '2': {
      //       id: '2',
      //       label: 'Non-Conforme',
      //       value: '2',
      //       isKo: true,
      //     },
      //     '3': {
      //       id: '3',
      //       label: 'Sans Objet',
      //       value: '3',
      //       isKo: false,
      //     },
      //   },
      // },
      // {
      //   control_answer_choices: [
      //     {
      //       choice_id: '1',
      //       choice_is_ko: false,
      //       choice_lib: 'Conforme',
      //     },
      //     {
      //       choice_id: '2',
      //       choice_is_ko: true,
      //       choice_lib: 'Non-Conforme',
      //     },
      //     {
      //       choice_id: '3',
      //       choice_is_ko: false,
      //       choice_lib: 'Sans Objet',
      //     },
      //   ],
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: true,
      //   control_family: 'standard',
      //   control_id: '2314',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: 'int',
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title: 'Valeur E : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
      //   control_type: 'selectlist',
      //   control_value: null,
      //   answerChoices: {
      //     '1': {
      //       id: '1',
      //       label: 'Conforme',
      //       value: '1',
      //       isKo: false,
      //     },
      //     '2': {
      //       id: '2',
      //       label: 'Non-Conforme',
      //       value: '2',
      //       isKo: true,
      //     },
      //     '3': {
      //       id: '3',
      //       label: 'Sans Objet',
      //       value: '3',
      //       isKo: false,
      //     },
      //   },
      // },
      // {
      //   control_answer_choices: [
      //     {
      //       choice_id: '1',
      //       choice_is_ko: false,
      //       choice_lib: 'Conforme',
      //     },
      //     {
      //       choice_id: '2',
      //       choice_is_ko: true,
      //       choice_lib: 'Non-Conforme',
      //     },
      //     {
      //       choice_id: '3',
      //       choice_is_ko: false,
      //       choice_lib: 'Sans Objet',
      //     },
      //   ],
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: true,
      //   control_family: 'standard',
      //   control_id: '2315',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: 'int',
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title: 'Valeur F : Conforme(1) ; Non-Conforme+Sans_Objet(0)',
      //   control_type: 'selectlist',
      //   control_value: null,
      //   answerChoices: {
      //     '1': {
      //       id: '1',
      //       label: 'Conforme',
      //       value: '1',
      //       isKo: false,
      //     },
      //     '2': {
      //       id: '2',
      //       label: 'Non-Conforme',
      //       value: '2',
      //       isKo: true,
      //     },
      //     '3': {
      //       id: '3',
      //       label: 'Sans Objet',
      //       value: '3',
      //       isKo: false,
      //     },
      //   },
      // },
      // {
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: false,
      //   control_family: 'formula',
      //   control_id: '2316',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: null,
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title:
      //     'Avg_Simple(D;E;F) : Pas de coef ; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
      //   control_type: 'formula',
      //   control_value: null,
      //   formula: {
      //     formula: '(#2313+#2314+#2315)/3',
      //     map: null,
      //   },
      // },
      // {
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: false,
      //   control_family: 'formula',
      //   control_id: '2317',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: null,
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title:
      //     'Avg_Coef(D;E;F) : Coef =>10-20-70; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
      //   control_type: 'formula',
      //   control_value: null,
      //   formula: {
      //     formula: '(#2313*10+#2314*20+#2315*70)/100',
      //     map: null,
      //   },
      // },
      // {
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: false,
      //   control_family: 'formula',
      //   control_id: '2318',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: null,
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title:
      //     'Avg_Coef(D;E;F) : Coef =>25-50-25; Scale=>0-45:Bad;45-85:Mean;85-100:Ok',
      //   control_type: 'formula',
      //   control_value: null,
      //   formula: {
      //     formula: '(#2313*25+#2314*50+#2315*25)/100',
      //     map: null,
      //   },
      // },
      // {
      //   control_conditional: false,
      //   control_desc_1: 'null',
      //   control_desc_2: null,
      //   control_editable: false,
      //   control_family: 'formula',
      //   control_id: '2319',
      //   control_manage_compliance: false,
      //   control_mandatory: false,
      //   control_pg_base_type: null,
      //   control_previous_value: null,
      //   control_regex: null,
      //   control_regex_msg: null,
      //   control_title: 'Contagion (D;E;F) ; Conforme/Non-Conforme',
      //   control_type: 'formula',
      //   control_value: null,
      //   formula: {
      //     formula: '(#2313+#2314+#2315)/3',
      //     map: null,
      //   },
      // },
    ]);
  });
  it('Return controls', () => {
    mockFn(controls);
    expect(mockFn).toBeCalled();
    expect(mockFn).toHaveReturned();
  });
});
