name: Deploy
on:
    push:
        branches:
            - 'staging'

jobs:
    tests:
        name: Tests
        uses: ./.github/workflows/tests.yml
    deploy-staging:
        if: success() && (github.event_name == 'push')
        name: Deploy-staging
        runs-on: ubuntu-20.04
        needs: [tests]
        continue-on-error: false

        steps:
            -   name: checkout
                uses: actions/checkout@v4

            -   name: setup node
                uses: actions/setup-node@v4
                with:
                    node-version: 20.11.0

            -   name: yarn install
                run: yarn install

            -   name: create .env
                run: cp .env .env.production

            -   name: yarn build
                run: CI='' yarn run build --profile

            -   name: copy Dockerfile and nginx conf
                run: |
                    cp ci/staging/Dockerfile Dockerfile
                    cp ci/staging/nginx.conf nginx.conf

            -   name: building docker image
                run: docker build -t ghcr.io/deltarm/cp1-front/github-staging:latest -f ci/staging/Dockerfile .

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: pushing docker image
                run: docker push ghcr.io/deltarm/cp1-front/github-staging:latest

            -   name: Deploy on Server
                uses: burnett01/rsync-deployments@5.1
                with:
                    switches: -av --include="docker-compose.*" --exclude="*"
                    path: .
                    remote_path: ${{ secrets.SSH_STAGING_DIRECTORY_BUILD_CP1 }}
                    remote_host: ${{ secrets.SSH_STAGING_HOST_CP1 }}
                    remote_user: ${{ secrets.SSH_COMMON_USER_CP1 }}
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY_COMMON_CP1 }}

            -   name : Install on Server
                uses: JimCronqvist/action-ssh@0.1.1
                with:
                    hosts: ${{ secrets.SSH_COMMON_USER_CP1 }}@${{ secrets.SSH_STAGING_HOST_CP1 }}
                    privateKey: ${{ secrets.SSH_PRIVATE_KEY_COMMON_CP1 }}
                    command: |
                        docker login ghcr.io/deltarm/cp1-front/github-staging:latest -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
                        docker-compose -f /home/deltarm/client/docker-compose.staging_github.yml pull
                        docker-compose -f /home/deltarm/client/docker-compose.staging_github.yml down --remove-orphans
                        docker-compose -f /home/deltarm/client/docker-compose.staging_github.yml up -d --remove-orphans
